channel_towers: 32
number_of_scales: 3
initial_splits_per_scale: 6
latent_size: 20
input_dimension: 64
num_flows: 0
num_blocks_prepost: 1
num_cells_per_block_prepost: 2
cells_per_split_enc: 2
cells_per_input_dec: 2
channel_multiplier : 2
exponential_scaling: 1
sampling_method: logistic_mixture
n_mix: 10
fixed_flows: False
training_parameters:
  learning_rate: 0.01
  regularization_constant: 0.1
  kl_constant: 1
  warmup_epochs: 50
  batch_size: 32
  use_tensor_checkpoints: False
  half_precision: True
  write_reconstruction: False
  epochs_per_checkpoint: 1
  epochs: 200